[server]
host = "localhost"
port = 8080
ssl = true

[database]
type = "PostgreSQL"
max_connections = 20

[database.credentials]
user = "admin"
password = "secret"

[user_settings]
theme = "dark"

[user_settings.notifications]
email = false
sms = true

user_settings.favorites = ["Python", "OpenAI", "AI"]
